-- Energy Flex Trust v0.9 reference grants.
--
-- Preconditions:
--   * roles flextrust_migrator, flextrust_api, flextrust_worker and
--     flextrust_auditor already exist;
--   * migrations have been applied by a login that assumes flextrust_migrator;
--   * role credentials are provisioned outside this repository.
--
-- Re-run and review this file after every schema migration. It intentionally
-- grants no DELETE or DDL capability to runtime roles.

BEGIN;

REVOKE CREATE ON SCHEMA public FROM PUBLIC;
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM PUBLIC;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM PUBLIC;

GRANT USAGE, CREATE ON SCHEMA public TO flextrust_migrator;
GRANT USAGE ON SCHEMA public TO flextrust_api, flextrust_worker, flextrust_auditor;

-- API: execute the coordination workflow, append audit evidence and enqueue
-- outbound work. DELETE remains intentionally absent.
GRANT SELECT, INSERT, UPDATE ON TABLE
    assets,
    flex_offers,
    reservations,
    dispatches,
    meter_readings,
    settlements,
    audit_events,
    idempotency_records,
    outbox_messages
TO flextrust_api;

-- Worker: claim/finalize outbox messages, transition dispatch/reservation state,
-- and append/verify audit events. It cannot create offers, readings or settlements.
GRANT SELECT, UPDATE ON TABLE outbox_messages TO flextrust_worker;
GRANT SELECT, UPDATE ON TABLE dispatches, reservations TO flextrust_worker;
GRANT SELECT ON TABLE flex_offers, assets TO flextrust_worker;
GRANT SELECT, INSERT ON TABLE audit_events TO flextrust_worker;

-- Auditor: independent read-only verification path.
GRANT SELECT ON TABLE
    assets,
    flex_offers,
    reservations,
    dispatches,
    meter_readings,
    settlements,
    audit_events,
    idempotency_records,
    outbox_messages,
    alembic_version
TO flextrust_auditor;

-- audit_events.sequence is generated by a PostgreSQL sequence. API and worker
-- need only sequence consumption/inspection; no runtime role receives ownership.
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public
TO flextrust_api, flextrust_worker;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO flextrust_auditor;

COMMIT;
